version: '2'
services:
    desafiohu3-mysql:
        container_name: desafiohu3-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/desafiohu3/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=desafiohu3
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
